function loadItalianChannels(){
 const url=new URL('italia.m3u',location.href).href;
 const selected=[{"name":"Rai News 24","group":"Notizie Italia","url":"https://d3k8wzt41aflvx.cloudfront.net/RAINEWS24/Live.m3u8","logo":""},{"name":"TGCOM24","group":"Notizie Italia","url":"https://live02-seg.msf.cdn.mediaset.net/live/ch-kf/kf-clr.isml/index.m3u8","logo":""},{"name":"TV2000","group":"Cultura e società","url":"https://hls-live-tv2000.akamaized.net/hls/live/2028510/tv2000/master.m3u8","logo":""},{"name":"Senato TV","group":"Istituzioni","url":"https://senato-live.morescreens.com/SENATO_1_001/playlist.m3u8","logo":""},{"name":"Camera dei Deputati","group":"Istituzioni","url":"https://video-ar.radioradicale.it/diretta/camera2/playlist.m3u8","logo":""},{"name":"Sportitalia SoloCalcio","group":"Sport","url":"https://distribution.sportitalialive.it/sportitalia/sisolocalcio_abr/playlist.m3u8","logo":""},{"name":"TeleAmbiente","group":"Territorio","url":"https://5f22d76e220e1.streamlock.net/teleambiente2024/teleambiente2024/playlist.m3u8","logo":""}];
 channels=selected;
 const stored=storePlaylist(url);
 $('#url').value=url;
 $('#status').textContent='NOVA TV Italia: '+channels.length+' canali caricati'+(stored?' e salvati.':'. Il salvataggio locale non è disponibile.');
 activeGroup='Tutti';renderAll();tab('live');
}
const knownLogos={
'Rai News 24':'https://raw.githubusercontent.com/maginetweb-arch/TVITALIA/main/TVL/rainews24.png',
'TGCOM24':'https://raw.githubusercontent.com/maginetweb-arch/TVITALIA/main/TVL/tgcom24.png',
'TV2000':'https://cdn.jsdelivr.net/gh/sfiorini/IPTV-Italy/logos/tv2000.png',
'Senato TV':'https://www.senato.it/favicon.ico',
'Camera dei Deputati':'https://www.camera.it/favicon.ico',
'Sportitalia SoloCalcio':'https://www.sportitalia.com/favicon.ico',
'TeleAmbiente':'https://www.teleambiente.it/favicon.ico'
};
function channelLogo(c){return c.logo||knownLogos[c.name]||''}
const $=s=>document.querySelector(s);
let channels=[],currentTab='home',current=null,activeGroup='Tutti';
let playlists=[],activePlaylist='';const libraryKey='nova-playlists-v2';
function persistLibrary(){try{localStorage.setItem(libraryKey,JSON.stringify({playlists,activePlaylist}));return true}catch{return false}}
function renderPlaylistList(){const el=$('#playlist-list');el.replaceChildren();for(const p of playlists){const row=document.createElement('div');row.className='playlist-row';const label=document.createElement('strong');label.textContent=p.name+' · '+p.channels.length+' canali';const actions=document.createElement('div');const open=document.createElement('button');open.className='secondary';open.textContent=p.id===activePlaylist?'Attiva':'Apri';open.disabled=p.id===activePlaylist;open.onclick=()=>selectPlaylist(p.id);const del=document.createElement('button');del.className='secondary';del.textContent='Elimina';del.onclick=()=>{if(!confirm('Eliminare questa playlist?'))return;playlists=playlists.filter(x=>x.id!==p.id);selectPlaylist(p.id===activePlaylist?(playlists[0]?.id||''):activePlaylist)};actions.append(open,del);row.append(label,actions);el.append(row)}}
function selectPlaylist(id){const p=playlists.find(x=>x.id===id);activePlaylist=p?.id||'';channels=p?.channels||[];$('#url').value=p?.url||'';activeGroup='Tutti';persistLibrary();renderPlaylistList();renderAll()}

const playlistKey='nova-playlist-v1';
function restorePlaylist(){try{const lib=JSON.parse(localStorage.getItem(libraryKey)||'null');if(lib&&Array.isArray(lib.playlists)){playlists=lib.playlists;selectPlaylist(lib.activePlaylist||playlists[0]?.id||'');return}const data=JSON.parse(localStorage.getItem(playlistKey)||'null');if(data&&Array.isArray(data.channels)){channels=data.channels.filter(c=>typeof c.name==='string'&&typeof c.url==='string'&&/^https?:\/\//.test(c.url)).slice(0,20000);$('#url').value=data.url||'';$('#status').textContent='Playlist precedente recuperata.';playlists=[{id:'legacy',name:'La mia playlist',url:data.url||'',channels}];activePlaylist='legacy';persistLibrary();renderPlaylistList();}}catch{}}
function storePlaylist(url){let p=playlists.find(x=>x.url===url);if(p)p.channels=channels;else{p={id:'p'+Date.now(),name:url.endsWith('/demo.m3u')?'Demo':'Playlist '+(playlists.length+1),url,channels};playlists.push(p)}activePlaylist=p.id;renderPlaylistList();return persistLibrary()}

const saved=()=>{try{return JSON.parse(localStorage.getItem('nova-favorites')||'[]')}catch{return []}};
let favorites=saved();
const historyKey='nova-history-v1';
function getHistory(){try{const data=JSON.parse(localStorage.getItem(historyKey)||'[]');return Array.isArray(data)?data:[]}catch{return []}}
let history=getHistory();
function renderHistory(){const items=history.map(h=>channels.find(c=>c.url===h.url)).filter(Boolean).slice(0,8);$('#continue-section').classList.toggle('hidden',!items.length);fill($('#continue-list'),items,'Nessun contenuto recente.')}
$('#clear-history').onclick=()=>{history=[];try{localStorage.removeItem(historyKey)}catch{}renderHistory()};
function tab(name){currentTab=name;for(const id of ['home','live','national','apps','favorites','settings','watch','detail'])$('#'+id).classList.toggle('hidden',id!==name);document.querySelectorAll('.nav[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===name));if(name==='favorites')renderFavorites();if(name==='live')renderChannels();window.scrollTo(0,0)}
document.querySelectorAll('[data-tab]').forEach(b=>b.addEventListener('click',()=>tab(b.dataset.tab)));
$('#hero-action').onclick=()=>tab(channels.length?'live':'settings');$('#back-live').onclick=()=>{ $('#player').pause();tab('live')};
function parseM3U(text){let name='',group='Generale',logo='',out=[];for(const raw of text.split(/\r?\n/)){const line=raw.trim();if(line.startsWith('#EXTINF:')){name=line.split(',').slice(1).join(',').trim()||'Canale';group=(line.match(/group-title="([^"]*)"/)||[])[1]||'Generale';logo=(line.match(/tvg-logo="([^"]*)"/)||[])[1]||'';}else if(line&&!line.startsWith('#')){try{const url=new URL(line);if(['https:','http:'].includes(url.protocol))out.push({name:name||'Canale',url:url.href,group,logo})}catch{}name='';group='Generale';logo=''}}return out}
function isFav(c){return favorites.includes(c.url)}
function toggleFav(c){favorites=isFav(c)?favorites.filter(x=>x!==c.url):[...favorites,c.url];localStorage.setItem('nova-favorites',JSON.stringify(favorites));renderAll()}
function tile(c){const b=document.createElement('article');b.className='tile';const poster=document.createElement('div');poster.className='poster';if(channelLogo(c)){try{const u=new URL(channelLogo(c));if(u.protocol==='https:'){const img=document.createElement('img');img.src=u.href;img.alt='';img.loading='lazy';img.style.cssText='max-width:75%;max-height:75%;object-fit:contain';img.onerror=()=>{img.remove();poster.textContent='▶'};poster.append(img)}else poster.textContent='▶'}catch{poster.textContent='▶'}}else poster.textContent='▶';const info=document.createElement('div');info.className='tile-info';const title=document.createElement('strong');title.textContent=c.name;const meta=document.createElement('small');meta.textContent=c.group||'Streaming';const fav=document.createElement('button');fav.className='nav';fav.textContent=isFav(c)?'♥':'♡';fav.setAttribute('aria-label','Preferito '+c.name);fav.onclick=()=>toggleFav(c);const details=document.createElement('button');details.className='nav';details.textContent='ⓘ';details.setAttribute('aria-label','Dettagli '+c.name);details.onclick=()=>showDetails(c);info.append(title,meta,details,fav);poster.setAttribute('role','button');poster.setAttribute('tabindex','0');poster.setAttribute('aria-label','Riproduci '+c.name);poster.style.cursor='pointer';poster.style.userSelect='none';poster.style.webkitUserSelect='none';poster.style.webkitTouchCallout='none';poster.addEventListener('click',()=>watch(c));poster.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();watch(c)}});b.append(poster,info);b.setAttribute('aria-label',c.name+' · '+(c.group||'Streaming'));return b}
function showDetails(c){$('#detail-title').textContent=c.name;$('#detail-group').textContent=c.group||'Generale';$('#detail-source').textContent=playlists.find(p=>p.id===activePlaylist)?.name||'Playlist';$('#detail-play').onclick=()=>watch(c);$('#detail-favorite').textContent=isFav(c)?'♥ Rimuovi dai preferiti':'♡ Aggiungi ai preferiti';$('#detail-favorite').onclick=()=>{toggleFav(c);showDetails(c)};const el=$('#detail-logo');el.replaceChildren();if(channelLogo(c)){try{const u=new URL(channelLogo(c));if(u.protocol==='https:'){const img=document.createElement('img');img.src=u.href;img.alt='Logo';el.append(img)}}catch{}}tab('detail')}
function fill(node,items,message){node.replaceChildren();if(!items.length){const p=document.createElement('div');p.className='empty';p.textContent=message;node.append(p)}else items.forEach(c=>node.append(tile(c)))}
function renderChannels(){const q=$('#search').value.toLocaleLowerCase('it');const all=channels.filter(c=>c.name.toLocaleLowerCase('it').includes(q));const found=activeGroup==='Tutti'?all:all.filter(c=>(c.group||'Generale')===activeGroup);const filters=$('#category-filters');if(filters){filters.replaceChildren();for(const group of ['Tutti',...new Set(channels.map(c=>c.group||'Generale'))]){const btn=document.createElement('button');btn.className='nav category-chip'+(group===activeGroup?' active':'');btn.textContent=group;btn.onclick=()=>{activeGroup=group;renderChannels()};filters.append(btn)}}$('#count').textContent=found.length+' canali';const groups=[...new Set(found.map(c=>c.group||'Generale'))];const target=$('#channels');target.replaceChildren();if(!found.length){fill(target,[], 'Nessun canale. Importa una playlist dalla sezione Playlist.')}else for(const group of groups){const title=document.createElement('h2');title.textContent=group;title.style.cssText='grid-column:1/-1;font-size:18px;margin:16px 0 0';target.append(title);found.filter(c=>(c.group||'Generale')===group).forEach(c=>target.append(tile(c)))}}
function renderFavorites(){fill($('#favorites-list'),channels.filter(isFav),'Nessun preferito. Tocca il cuore accanto a un canale.')}
function renderAll(){fill($('#featured'),channels.slice(0,8),'La tua selezione apparirà qui dopo aver importato una playlist.');renderChannels();renderFavorites();renderHistory()}
function watch(c){history=[{url:c.url},...history.filter(h=>h.url!==c.url)].slice(0,20);try{localStorage.setItem(historyKey,JSON.stringify(history))}catch{}renderHistory();current=c;$('#watch-title').textContent=c.name;$('#now').textContent=c.name;const player=$('#player');player.pause();player.src=c.url;player.load();tab('watch');player.play().catch(()=>{ $('#now').textContent=c.name+' · Premi Play nel lettore per avviare il video.'; });}
async function load(urlText){let url;try{url=new URL(urlText);if(url.protocol!=='https:')throw Error('URL HTTPS richiesto')}catch{$('#status').textContent='Inserisci un URL HTTPS valido.';return}$('#load').disabled=true;$('#status').textContent='Caricamento…';try{const controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),15000);let response;try{response=await fetch(url,{signal:controller.signal})}finally{clearTimeout(timeout)}if(!response.ok)throw Error('HTTP '+response.status);const text=await response.text();if(text.length>5000000)throw Error('Playlist troppo grande');const parsed=parseM3U(text);if(!parsed.length)throw Error('Nessun canale valido');channels=parsed;const stored=storePlaylist(url.href);$('#status').textContent=channels.length+' canali importati'+(stored?' e salvati sul dispositivo.':'. Memoria locale non disponibile.');renderAll();tab('live')}catch(e){ $('#status').textContent='Importazione non riuscita: '+e.message+'. Verifica anche i permessi CORS.'}finally{$('#load').disabled=false}}
$('#load').onclick=()=>load($('#url').value);$('#demo').onclick=()=>{$('#url').value=new URL('demo.m3u',location.href).href;load($('#url').value)};$('#italia-channels').onclick=loadItalianChannels;$('#free-channels').onclick=()=>{$('#url').value=new URL('free-channels.m3u',location.href).href;load($('#url').value)};$('#demo2').onclick=()=>{$('#url').value=new URL('demo-2.m3u',location.href).href;load($('#url').value)};$('#search').oninput=renderChannels;$('#detail-back').onclick=()=>tab('live');restorePlaylist();renderAll();
